- name: Playbook for podman.
  become: true
  hosts: soufe1
  tasks:
    - name: Create mount directory haproxy
      file:
       path: /usr/local/etc/haproxy
       state: directory
       mode: '0755'

    - name: Create mount directory certificati
      file:
       path: /usr/local/etc/certificati
       state: directory
       mode: '0755'

    - name: Copy the haproxy.cfg to mount directory
      copy:
       src: /home/vagrant/.ansible/haproxy.cfg
       dest: /usr/local/etc/haproxy/haproxy.cfg

    - name: Copy the certifcato to mount directory
      copy:
       src: /home/vagrant/.ansible/certificati/certificato.pem
       dest: /usr/local/etc/certificati/certificato.pem

    - name: Running httpd image.
      containers.podman.podman_container:
         name: haproxytech
         image: docker.io/haproxy
         volumes: 
             - /usr/local/etc/haproxy/:/usr/local/etc/haproxy/
             - /usr/local/etc/certificati:/usr/local/etc/haproxy/certificati
